using Microsoft.Xna.Framework;

namespace Merthsoft.Moose.GravityCa;
internal static class Palettes
{
    public static Color[] Rainbow = [Color.Red, Color.Orange, Color.Yellow, Color.Green, Color.Blue, Color.Indigo, Color.Violet];
    public static Color[] ReverseRainbow = [Color.Violet, Color.Indigo, Color.Blue, Color.Green, Color.Yellow, Color.Orange, Color.Red];
    public static Color[] TenRainbow = [
        ..Rainbow, ..ReverseRainbow,
        ..Rainbow, ..ReverseRainbow,
        ..Rainbow, ..ReverseRainbow,
        ..Rainbow, ..ReverseRainbow,
        ..Rainbow, ..ReverseRainbow ];
    
    public static Color[] HundredRainbow = [..TenRainbow, ..TenRainbow, ..TenRainbow, ..TenRainbow, ..TenRainbow, ..TenRainbow, ..TenRainbow, ..TenRainbow, ..TenRainbow, ..TenRainbow];
    public static Color[] MultiBlackWhite = [Color.Black, Color.White, Color.Black, Color.White, Color.Black, Color.White, Color.Black, Color.White];
    public static Color[] HundredBlackWhite = [..MultiBlackWhite, ..MultiBlackWhite, ..MultiBlackWhite, ..MultiBlackWhite, ..MultiBlackWhite,
            ..MultiBlackWhite, ..MultiBlackWhite, ..MultiBlackWhite, ..MultiBlackWhite, ..MultiBlackWhite,
            ..MultiBlackWhite, ..MultiBlackWhite, ..MultiBlackWhite, ..MultiBlackWhite, ..MultiBlackWhite,
            ..MultiBlackWhite, ..MultiBlackWhite, ..MultiBlackWhite, ..MultiBlackWhite, ..MultiBlackWhite,
            ..MultiBlackWhite, ..MultiBlackWhite, ..MultiBlackWhite, ..MultiBlackWhite, ..MultiBlackWhite,
            ..MultiBlackWhite, ..MultiBlackWhite, ..MultiBlackWhite, ..MultiBlackWhite, ..MultiBlackWhite,
            ..MultiBlackWhite, ..MultiBlackWhite, ..MultiBlackWhite, ..MultiBlackWhite, ..MultiBlackWhite,
            ..MultiBlackWhite, ..MultiBlackWhite, ..MultiBlackWhite, ..MultiBlackWhite, ..MultiBlackWhite,
            ..MultiBlackWhite, ..MultiBlackWhite, ..MultiBlackWhite, ..MultiBlackWhite, ..MultiBlackWhite,
            ..MultiBlackWhite, ..MultiBlackWhite, ..MultiBlackWhite, ..MultiBlackWhite, ..MultiBlackWhite,
            ..MultiBlackWhite, ..MultiBlackWhite, ..MultiBlackWhite, ..MultiBlackWhite, ..MultiBlackWhite,
            ..MultiBlackWhite, ..MultiBlackWhite, ..MultiBlackWhite, ..MultiBlackWhite, ..MultiBlackWhite,
            ..MultiBlackWhite, ..MultiBlackWhite, ..MultiBlackWhite, ..MultiBlackWhite, ..MultiBlackWhite,
            ..MultiBlackWhite, ..MultiBlackWhite, ..MultiBlackWhite, ..MultiBlackWhite, ..MultiBlackWhite,
            ..MultiBlackWhite, ..MultiBlackWhite, ..MultiBlackWhite, ..MultiBlackWhite, ..MultiBlackWhite,
            ..MultiBlackWhite, ..MultiBlackWhite, ..MultiBlackWhite, ..MultiBlackWhite, ..MultiBlackWhite,
            ..MultiBlackWhite, ..MultiBlackWhite, ..MultiBlackWhite, ..MultiBlackWhite, ..MultiBlackWhite,
            ..MultiBlackWhite, ..MultiBlackWhite, ..MultiBlackWhite, ..MultiBlackWhite, ..MultiBlackWhite,
            ..MultiBlackWhite, ..MultiBlackWhite, ..MultiBlackWhite, ..MultiBlackWhite, ..MultiBlackWhite,
            ..MultiBlackWhite, ..MultiBlackWhite, ..MultiBlackWhite, ..MultiBlackWhite, ..MultiBlackWhite,];


    public static Color[][] AllPalettes = [
        [
            Color.Black,
            Color.White
        ], 
        [
            Color.Black,
            ..Rainbow,
            Color.White
        ], 
        [
            ..HundredBlackWhite, ..HundredBlackWhite
        ],
        [
            ..HundredBlackWhite, ..HundredBlackWhite, ..HundredBlackWhite, ..HundredBlackWhite, ..HundredBlackWhite,
            ..HundredBlackWhite, ..HundredBlackWhite, ..HundredBlackWhite, ..HundredBlackWhite, ..HundredBlackWhite,
        ],
        [
            ..HundredBlackWhite, ..HundredBlackWhite, ..HundredBlackWhite, ..HundredBlackWhite, ..HundredBlackWhite,
            ..HundredBlackWhite, ..HundredBlackWhite, ..HundredBlackWhite, ..HundredBlackWhite, ..HundredBlackWhite,
            ..HundredBlackWhite, ..HundredBlackWhite, ..HundredBlackWhite, ..HundredBlackWhite, ..HundredBlackWhite,
            ..HundredBlackWhite, ..HundredBlackWhite, ..HundredBlackWhite, ..HundredBlackWhite, ..HundredBlackWhite,
            ..HundredBlackWhite, ..HundredBlackWhite, ..HundredBlackWhite, ..HundredBlackWhite, ..HundredBlackWhite, 
            ..HundredBlackWhite, ..HundredBlackWhite, ..HundredBlackWhite, ..HundredBlackWhite, ..HundredBlackWhite, 
            ..HundredBlackWhite, ..HundredBlackWhite, ..HundredBlackWhite, ..HundredBlackWhite, ..HundredBlackWhite, 
            ..HundredBlackWhite, ..HundredBlackWhite, ..HundredBlackWhite, ..HundredBlackWhite, ..HundredBlackWhite,
            ..HundredBlackWhite, ..HundredBlackWhite, ..HundredBlackWhite, ..HundredBlackWhite, ..HundredBlackWhite,
            ..HundredBlackWhite, ..HundredBlackWhite, ..HundredBlackWhite, ..HundredBlackWhite, ..HundredBlackWhite,
            ..HundredBlackWhite, ..HundredBlackWhite, ..HundredBlackWhite, ..HundredBlackWhite, ..HundredBlackWhite,
            
        ], 
        [
            Color.DarkRed,
            ..TenRainbow,
            Color.White,
            Color.Black
        ], 
        [
            Color.DarkRed,
            ..TenRainbow,
            ..TenRainbow,
            ..TenRainbow,
            Color.White,
            Color.Black
        ], 
        [
            Color.White,
            ..Rainbow,
            ..Rainbow,
            ..Rainbow,
            ..Rainbow,
            ..Rainbow,
            ..Rainbow,
            ..Rainbow,
            ..Rainbow,
            ..Rainbow,
            ..Rainbow,
            ..Rainbow,
            ..Rainbow,
            ..Rainbow,
            ..Rainbow,
            ..Rainbow,
            ..Rainbow,
            Color.White,
            Color.Black
        ], 
        [
            Color.Black,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            Color.White,
            Color.Black
        ], 
        [
            Color.Black,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            Color.White,
            Color.Black
        ]
    ];
}
