using Microsoft.Xna.Framework;

namespace Merthsoft.Moose.GravityCa;
internal static class Palettes
{
    public static Color[] Rainbow = [Color.Red, Color.Orange, Color.Yellow, Color.Green, Color.Blue, Color.Indigo, Color.Violet];
    public static Color[] ReverseRainbow = [Color.Violet, Color.Indigo, Color.Blue, Color.Green, Color.Yellow, Color.Orange, Color.Red];
    public static Color[] TenRainbow = [
        ..Rainbow, ..ReverseRainbow,
        ..Rainbow, ..ReverseRainbow,
        ..Rainbow, ..ReverseRainbow,
        ..Rainbow, ..ReverseRainbow,
        ..Rainbow, ..ReverseRainbow ];
    
    public static Color[] HundredRainbow = [..TenRainbow, ..TenRainbow, ..TenRainbow, ..TenRainbow, ..TenRainbow, ..TenRainbow, ..TenRainbow, ..TenRainbow, ..TenRainbow, ..TenRainbow];
    public static Color[] BlackWhite = [Color.SeaGreen, Color.HotPink];
    public static Color[] MultiBlackWhite = [..BlackWhite, ..BlackWhite, ..BlackWhite, ..BlackWhite];
    public static Color[] HundredBlackWhite = [..MultiBlackWhite, ..MultiBlackWhite, ..MultiBlackWhite, ..MultiBlackWhite, ..MultiBlackWhite,
            ..MultiBlackWhite, ..MultiBlackWhite, ..MultiBlackWhite, ..MultiBlackWhite, ..MultiBlackWhite,
            ..MultiBlackWhite, ..MultiBlackWhite, ..MultiBlackWhite, ..MultiBlackWhite, ..MultiBlackWhite,
            ..MultiBlackWhite, ..MultiBlackWhite, ..MultiBlackWhite, ..MultiBlackWhite, ..MultiBlackWhite,
            ..MultiBlackWhite, ..MultiBlackWhite, ..MultiBlackWhite, ..MultiBlackWhite, ..MultiBlackWhite,
            ..MultiBlackWhite, ..MultiBlackWhite, ..MultiBlackWhite, ..MultiBlackWhite, ..MultiBlackWhite,
            ..MultiBlackWhite, ..MultiBlackWhite, ..MultiBlackWhite, ..MultiBlackWhite, ..MultiBlackWhite,
            ..MultiBlackWhite, ..MultiBlackWhite, ..MultiBlackWhite, ..MultiBlackWhite, ..MultiBlackWhite,
            ..MultiBlackWhite, ..MultiBlackWhite, ..MultiBlackWhite, ..MultiBlackWhite, ..MultiBlackWhite,
            ..MultiBlackWhite, ..MultiBlackWhite, ..MultiBlackWhite, ..MultiBlackWhite, ..MultiBlackWhite,
            ..MultiBlackWhite, ..MultiBlackWhite, ..MultiBlackWhite, ..MultiBlackWhite, ..MultiBlackWhite,
            ..MultiBlackWhite, ..MultiBlackWhite, ..MultiBlackWhite, ..MultiBlackWhite, ..MultiBlackWhite,
            ..MultiBlackWhite, ..MultiBlackWhite, ..MultiBlackWhite, ..MultiBlackWhite, ..MultiBlackWhite,
            ..MultiBlackWhite, ..MultiBlackWhite, ..MultiBlackWhite, ..MultiBlackWhite, ..MultiBlackWhite,
            ..MultiBlackWhite, ..MultiBlackWhite, ..MultiBlackWhite, ..MultiBlackWhite, ..MultiBlackWhite,
            ..MultiBlackWhite, ..MultiBlackWhite, ..MultiBlackWhite, ..MultiBlackWhite, ..MultiBlackWhite,
            ..MultiBlackWhite, ..MultiBlackWhite, ..MultiBlackWhite, ..MultiBlackWhite, ..MultiBlackWhite,
            ..MultiBlackWhite, ..MultiBlackWhite, ..MultiBlackWhite, ..MultiBlackWhite, ..MultiBlackWhite,
            ..MultiBlackWhite, ..MultiBlackWhite, ..MultiBlackWhite, ..MultiBlackWhite, ..MultiBlackWhite,
            ..MultiBlackWhite, ..MultiBlackWhite, ..MultiBlackWhite, ..MultiBlackWhite, ..MultiBlackWhite,];


    public static Color[][] AllPalettes = [
        [
            Color.White,
            ..ReverseRainbow,
            Color.Black,
        ],
        [
            Color.Black,
            ..Rainbow,
            Color.White
        ],
        [
            ..BlackWhite
        ],
        [
            ..MultiBlackWhite,
        ],
        [
            ..HundredBlackWhite

        ],
        [
            Color.DarkRed,
            ..TenRainbow,
            Color.White,
            Color.Black
        ],
        [
            Color.DarkRed,
            ..TenRainbow,
            ..TenRainbow,
            ..TenRainbow,
            Color.White,
            Color.Black
        ],
        [
            Color.Black,
            ..HundredRainbow
        ],
        [
            Color.Black,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            Color.White,
            Color.Black
        ],
        [
            Color.Black,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow, ..HundredRainbow,
            Color.White,
            Color.Black
        ]
    ];
}
