namespace Merthsoft.Moose.Dungeon.Tiles;
public enum ItemTile
{
    None = -1,
    POTION_START = 0,
    PurplePotion = 0,
    OrangePotion,
    BluePotion,
    GreenPotion,
    RedPotion,
    POTION_END,

    WEAPON_START = 10,
    SilverAxe = 10,
    GoldenAxe,
    SilverHammer,
    GoldenHammer,
    SilverBow,
    GoldenBow,
    SilverSword,
    GoldenSword,
    SilverWand,
    GoldenWand,
    WEAPON_END,

    ARMOR_START = 20,
    SilverArmor = 20,
    GoldenArmor,
    GreenArmor,
    GreenCloak,
    PurpleCloak,
    RedCloak,
    ARMOR_END,

    TREASURE_START = 30,
    GoldenRing = 30,
    BronzeRing,
    SilverRing,
    LargeSilverPile,
    MediumSilverPile,
    SmallSilverPile,
    LargeGoldPile,
    MediumGoldPile,
    SmallGoldPile,
    JadeNecklace,
    FoxNecklace,
    TopazNecklace,
    EmeraldNecklace,
    DiamondNecklace,
    SilverCrossNecklace,
    GoldCrossNecklace,
    TREASURE_END,
    
    KEY_START = 50,
    SilverKey = 50,
    GoldenKey,
    ClosedLock,
    OpenLock,
    ClosedChest,
    OpenChest,
    KEY_END,

    SCROLL_START = 70,
    Scroll1 = 70,
    Scroll2,
    Scroll3,
    Scroll4,
    Scroll5,
    Scroll6,
    SROLL_END,

    MAP_START = 76,
    Map1 = 76,
    Map2, 
    Map3,
    Map4,

    FOOD_START = 80,
    Bread = 80,
    Meat,
    Cheese,
    RedMushroom,
    PurpleMushroom,
    BrownMushroom,
    FOOD_END,


    GraySpikes = 90,
    RedSpikes,
    Drawers,
    Shelf1,
    Shelf2,
    Shelf3,
}
