namespace Merthsoft.Moose.Dungeon.Tiles;
public enum DungeonTile
{
    None = -1,

    FLOOR_START = 0,
    GrayLargeCheckersFloor = 0,
    GraySmallCheckersFloor,
    GrayHollowCheckersFloor,
    GrayBrickFloor,
    GrayCobblestoneFloor,
    GrayHollowBrickFloor,
    GrayCirclesFloor,
    GrayPlusFloor,
    GrayStoneFloor,
    GrayDotsFloor,
    RedLargeCheckersFloor,
    RedSmallCheckersFloor,
    RedHollowCheckersFloor,
    RedBrickFloor,
    RedCobblestoneFloor,
    RedHollowBrickFloor,
    RedCirclesFloor,
    RedPlusFloor,
    RedStoneFloor,
    RedDotsFloor,
    FLOOR_END,

    DOOR_START = 20,
    GreenDoorHorizontal = 20,
    GreenDoorVertical,
    RedDoorHorizontal,
    RedDoorVertical,
    DOOR_END,

    StairsDown = 40,
    StairsUp,
    
    HorizontalTableLeft = 60,
    HorizontalTableMiddle,
    HorizontalTableRight,
    ChairRight,
    ChairLeft,
    ChairDown,
    ChairUp,
    VerticalTableLeft = 70,
    VerticalTableMiddle,
    VerticalTableRight,


    WALL_START = 80,
    StoneWall = 80,
    BrickWall,
    WALL_END,
}
